# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: thinksmart_development
  pool: 5
  username: root
  password: pranayama.777
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: thinksmart_production
  pool: 5
  username: thinksmart_production
  password: pranayama.777
  socket: /tmp/mysql.sock
