default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true
  database: thinksmart_development
  username: root
  password: 
  socket: /tmp/mysql.sock

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: thinksmart_development
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  host: b5oxbr2zss.database.windows.net
  database: thinksmart_production
  pool: 5
  username: thinksmart_production@b5oxbr2zss
  password: pranayama.777
  socket: /var/run/mysqld/mysqld.sock
  azure: true