# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true
  database: thinksmart_development
  username: root
  password: 
  socket: /tmp/mysql.sock

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: thinksmart_development
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: thinksmart_production
  pool: 5
  username: thinksmart_production
  password: pranayama.777
  socket: /var/lib/mysql/mysql.sock
